# Generated by Django 4.0.5 on 2022-07-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compositions', '0003_alter_composition_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.composition', verbose_name='Composition')),
            ],
        ),
        migrations.CreateModel(
            name='RanobeChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Chapter Number')),
                ('name', models.CharField(max_length=120, verbose_name='Chapter Title')),
                ('description', models.TextField(verbose_name='Chapter Description')),
            ],
        ),
        migrations.CreateModel(
            name='RanobeVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Volume Name')),
                ('ranobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.ranobe', verbose_name='Ranobe')),
            ],
        ),
        migrations.CreateModel(
            name='RanobeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ranobe Text')),
                ('translation', models.CharField(max_length=120, verbose_name='Translated by: ')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.ranobechapter', verbose_name='Ranobe Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='ranobechapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.ranobevolume', verbose_name='Ranobe Volume'),
        ),
    ]
