# Generated by Django 4.0.5 on 2022-07-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compositions', '0003_alter_composition_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.composition', verbose_name='Composition')),
            ],
        ),
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Chapter Number')),
                ('name', models.CharField(max_length=120, verbose_name='Chapter Title')),
                ('description', models.TextField(verbose_name='Chapter Description')),
            ],
        ),
        migrations.CreateModel(
            name='MangaVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Volume Number')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga', verbose_name='Manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Page of Manga Chapter')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('translation', models.CharField(max_length=120, verbose_name='Translated by: ')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangachapter', verbose_name='Manga Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangavolume', verbose_name='Manga Volume'),
        ),
    ]
