# Generated by Django 4.0.5 on 2022-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='description',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
