# Generated by Django 4.0.5 on 2022-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_composition_image_alter_composition_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
