# Generated by Django 4.0.5 on 2022-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0003_alter_composition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
